# Generated by Django 3.1.2 on 2020-10-14 17:59

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_audited_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(limit_choices_to={'asset_model__is_container': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.asset', validators=[inventory.models.location_validator]),
        ),
    ]
