# Generated by Django 3.0.4 on 2020-03-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_container', models.BooleanField(default=False, verbose_name='Can contain assets')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.AssetManufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=11)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('condition', models.CharField(choices=[('U', 'Unknown'), ('B', 'Broken'), ('A', 'Needs Assembly'), ('R', 'Needs Repair'), ('W', 'Working')], default='U', max_length=2)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.AssetModel')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Asset')),
            ],
        ),
    ]
