# Generated by Django 3.0.4 on 2020-03-05 14:34

import django.db.models.deletion
import inventory.asset_code
from django.conf import settings
from django.db import migrations, models


def add_root_assets(apps, schema_editor):
    Asset = apps.get_model("inventory", "Asset")
    AssetModel = apps.get_model("inventory", "AssetModel")
    AssetManufacturer = apps.get_model("inventory", "AssetManufacturer")

    org = settings.INVENTORY_ORG

    man = AssetManufacturer(name=org)
    man.save()

    model = AssetModel(name="Location", is_container=True, asset_manufacturer=man)
    model.save()

    world = Asset(
        name="World",
        asset_code="SRO-WOR-LDI",
        location_id=None,
        asset_model=model,
        condition="U",
        notes="The world. The root location for everything.",
    )
    world.save()

    world.location = world
    world.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetManufacturer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "is_container",
                    models.BooleanField(
                        default=False, verbose_name="Can contain assets"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.AssetManufacturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(
                        default=inventory.asset_code.generate_asset_code,
                        max_length=11,
                        unique=True,
                        validators=[inventory.asset_code.validate_asset_code],
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("U", "Unknown"),
                            ("B", "Broken"),
                            ("A", "Needs Assembly"),
                            ("R", "Needs Repair"),
                            ("W", "Working"),
                        ],
                        default="U",
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.AssetModel",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.Asset",
                    ),
                ),
            ],
        ),
        migrations.RunPython(code=add_root_assets,),
        migrations.AlterField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Asset"
            ),
        ),
    ]
