# Generated by Django 3.0.4 on 2020-03-05 14:05

from django.db import migrations
from django.conf import settings


def add_root_assets(apps, schema_editor):
    Asset = apps.get_model("inventory", "Asset")
    AssetModel = apps.get_model("inventory", "AssetModel")
    AssetManufacturer = apps.get_model("inventory", "AssetManufacturer")

    org = settings.INVENTORY_ORG

    man = AssetManufacturer(name=org)
    man.save()

    model = AssetModel(name="Location", is_container=True, asset_manufacturer=man)
    model.save()

    world = Asset(
        name="World",
        asset_code='SRO-WOR-LDN',
        location_id=None,
        asset_model=model,
        condition='U',
        notes="The world. The root location for everything.",
    )
    world.save()

    world.location = world
    world.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_root_assets)
    ]
