# Generated by Django 3.0.4 on 2020-03-09 00:43

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("inventory", "0003_auto_20200308_2346"),
        ("inventory", "0004_auto_20200308_2353"),
    ]

    dependencies = [
        (
            "inventory",
            "0002_historicalasset_historicalassetmanufacturer_historicalassetmodel",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.Asset",
                validators=[inventory.models.location_validator],
            ),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.Asset",
                validators=[inventory.models.location_validator],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="condition",
            field=models.CharField(
                choices=[
                    ("U", "Unknown"),
                    ("B", "Broken"),
                    ("D", "Disposed"),
                    ("A", "Needs Assembly"),
                    ("R", "Needs Repair"),
                    ("W", "Working"),
                ],
                default="U",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="condition",
            field=models.CharField(
                choices=[
                    ("U", "Unknown"),
                    ("B", "Broken"),
                    ("D", "Disposed"),
                    ("A", "Needs Assembly"),
                    ("R", "Needs Repair"),
                    ("W", "Working"),
                ],
                default="U",
                max_length=2,
            ),
        ),
    ]
