# Generated by Django 3.0.4 on 2020-03-08 23:46

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_historicalasset_historicalassetmanufacturer_historicalassetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Asset', validators=[inventory.models.location_validator]),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Asset', validators=[inventory.models.location_validator]),
        ),
    ]
