# Generated by Django 3.0.4 on 2020-03-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200308_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('U', 'Unknown'), ('B', 'Broken'), ('D', 'Disposed'), ('A', 'Needs Assembly'), ('R', 'Needs Repair'), ('W', 'Working')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='condition',
            field=models.CharField(choices=[('U', 'Unknown'), ('B', 'Broken'), ('D', 'Disposed'), ('A', 'Needs Assembly'), ('R', 'Needs Repair'), ('W', 'Working')], default='U', max_length=2),
        ),
    ]
