# Generated by Django 3.0.4 on 2020-03-10 13:04

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_consumable_asset_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(limit_choices_to={'asset_model__is_container': True}, on_delete=django.db.models.deletion.PROTECT, to='inventory.Asset', validators=[inventory.models.location_validator]),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='location',
            field=models.ForeignKey(limit_choices_to={'asset_model__is_container': True}, on_delete=django.db.models.deletion.PROTECT, to='inventory.Asset'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'asset_model__is_container': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Asset', validators=[inventory.models.location_validator]),
        ),
        migrations.AlterField(
            model_name='historicalconsumable',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'asset_model__is_container': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Asset'),
        ),
    ]
