# Generated by Django 3.0.4 on 2020-03-12 18:24

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_limit_location_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="audited_at",
            field=models.DateTimeField(
                default=datetime.datetime(2016, 6, 23, 16, 20, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="audited_at",
            field=models.DateTimeField(
                default=datetime.datetime(2016, 6, 23, 16, 20, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
