# Generated by Django 2.2.6 on 2019-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('counter', models.IntegerField()),
                ('secret', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('view_access_codes', 'View Access Codes'), ('increment_access_codes', 'Increment Access Codes')),
            },
        ),
    ]
